batch_size: 256
experiment_name: pcl_test
#experiment_name: simclr_flip_test_801_use_exp
root: ./dataset/RAFDB/img/aligned
train: ./dataset/RAFDB/img/train_list.txt
val: ./dataset/RAFDB/img/test_list.txt
test: ./dataset/RAFDB/img/test_list.txt
gpu_ids: '0'
dataset: 'RAFDB' # BU3D or RAFDB
start_epochs: 0
neg_alpha: 1.6
pose_alpha: 0.1
wd: 1.0e-3
T: 0.07
num_threads: 3
save_epoch: 100
dim: 512
#linear_dim: 512
linear_dim: 6272
checkpoint_dir: ./checkpoints
epochs: 6000
continue_train: False
eval: True
eval_mode: 'exp' # 'exp' or 'pose' or 'face_cycle'
eval_epochs: 300
seed: 3456
log_path: ./logs
model_name: exppose # 小写
dataset_name: lineardb # 小写
img_size: 100  # train 64 eval 100
lr: 1.0e-4
print_img: 50
print_loss : 20
load_model: ./checkpoints/pcl/best.pth
save_img_dir: ./save_img
save_img: False
print_network: False
classes_num: 7
linear_lr: 1.0e-2
warm_up: -1